#!/usr/bin/env bash
# Swap the model pinned to llama-server.service.
#
# Usage: set-llama-model.sh <absolute-path-to-gguf>
#
# Writes a systemd drop-in at /etc/systemd/system/llama-server.service.d/model.conf
# with `Environment=MODEL=<path>`, reloads systemd, clears any failed state,
# and restarts the unit so the new model is loaded.
#
# Installed to /usr/local/sbin/ml-stack-set-llama-model by 10-install-systemd.sh
# and allowed via /etc/sudoers.d/ml-stack-services so the dashboard user can
# invoke it through sudo -n without a password. Runs as root.
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <absolute-path-to-gguf>" >&2
    exit 64
fi

MODEL=$1

# ── guardrails ────────────────────────────────────────────────────────────
# Absolute path only, no '..', must be a regular file ending in .gguf, and
# must live in a trusted root so a tricked dashboard caller can't point the
# unit at /etc/shadow or similar.
if [[ "$MODEL" != /* || "$MODEL" == *..* ]]; then
    echo "invalid path: $MODEL" >&2; exit 65
fi
if [[ "$MODEL" != *.gguf ]]; then
    echo "must be a .gguf: $MODEL" >&2; exit 65
fi
if [[ ! -f "$MODEL" ]]; then
    echo "not a regular file: $MODEL" >&2; exit 66
fi
case "$MODEL" in
    /home/*/models/*.gguf) ;;
    /home/*/models/*/*.gguf) ;;
    /home/*/.lmstudio/models/*) ;;
    /root/models/*.gguf) ;;
    /root/models/*/*.gguf) ;;
    /var/lib/ml-stack-install/models/*.gguf) ;;
    /var/lib/ml-stack-install/models/*/*.gguf) ;;
    *)
        echo "refusing model outside trusted roots: $MODEL" >&2
        echo "  allowed: /home/<u>/models/**/*.gguf, /home/<u>/.lmstudio/models/*" >&2
        exit 67
        ;;
esac

# ── write drop-in ─────────────────────────────────────────────────────────
DROPIN_DIR=/etc/systemd/system/llama-server.service.d
mkdir -p "$DROPIN_DIR"

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<CONF
# Generated by set-llama-model.sh — do not edit by hand.
# Override the MODEL= set in the unit template with the user's selection.
[Service]
Environment=MODEL=$MODEL
CONF
install -m 0644 -o root -g root "$TMP" "$DROPIN_DIR/model.conf"

# ── reload + (re)start ────────────────────────────────────────────────────
systemctl daemon-reload
systemctl reset-failed llama-server.service 2>/dev/null || true
systemctl restart llama-server.service

echo "==> llama-server restarted with MODEL=$MODEL"
